### ISSUE TITLE
加载失败：internlm2-7b版本

### ISSUE THREAD

**Issue by IQ17** [scutcyr/SoulChat2.0#2]
您好，非常优秀的工作！

我在用AutoTokenizer.from_pretrained命令加载internlm2-7b版本模型时，一直遇到报错
No module named 'transformers_module.SoulChat2' 
请问应该怎么办呀？

谢谢！

**Comment by Xie-xiaojay** [comment]
你可以检查一下Transformers版本是不是4.43.0，或者用LLaMA-Factory（https://github.com/hiyouga/LLaMA-Factory ）这个项目进行推理。

**Comment by IQ17** [comment]
谢谢回复！ 
我的Transformer环境应该是可以的，我可以跑SoulChat2.0-Qwen2-7B 也可以跑 基座模型internlm2-chat-7b，但是依然上面的报错。
我主要是想要用vLLM这种框架做api部署，所以没有使用LLaMA-Factory。
